version: '3.7'

services:
  bernard:
    build: 
      context: bernard_project
    env_file:
      - .env
    volumes:
      - ./bernard_project:/code
    ports:
      - 8666:8666
    depends_on:
      - redis
    user: ${CURRENT_UID}
    network_mode: host
    entrypoint: [ "./run.sh" ]
    
  redis:
    image: redis:6.0.8-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
volumes:
  redis_data: