version: '3.7'

services:
  bernard:
    image: victorgrubio/bernard-bot-with-madrid:1.0.0
    environment:
      - BERNARD_SETTINGS_FILE
      - BERNARD_BASE_URL
      - WEBVIEW_SECRET_KEY
      - BASE_VIDEO_API_URL
      - VIDEO_NAME
      - TELEGRAM_TOKEN
    ports:
      - 8000:8666
    depends_on:
      - redis
    entrypoint: [ "./run.sh" ]
    
  redis:
    image: redis:6.0.8-alpine
    ports:
      - 6379:6379