version: 2.1
orbs:
  docker: circleci/docker@1.4.0
workflows:
  build-push-heroku-docker:
    jobs:
      - docker/hadolint:
          dockerfiles: bernard_project/Dockerfile
          context:
            - docker