version: 2.1
orbs:
  docker: circleci/docker@1.4.0
workflows:
  build-push-heroku-docker:
    jobs:
      - docker/hadolint:
          dockerfiles: bernard_project/Dockerfile
          context:
            - docker
      - docker/publish:
          dockerfile: Dockerfile
          image: victorgrubio/bernard-bot-with-madrid
          tag: 'latest,1.0.0'
          docker-context: bernard_project
          path: bernard_project
          context:
            - docker